In [1]:
import numpy as np

In [2]:
list1 = [2,3,4,5,6,2,7,6,8,9]

In [3]:
list1

[2, 3, 4, 5, 6, 2, 7, 6, 8, 9]

In [4]:
my_numpy_arr = np.array(list1)

In [5]:
my_numpy_arr

array([2, 3, 4, 5, 6, 2, 7, 6, 8, 9])

In [6]:
type(my_numpy_arr)

numpy.ndarray

In [7]:
#Now I wanna create a matrix using numpy
matrix1 = np.array([[2,3,4], [5,6,7]])
#the first square bracket is first row and the second with 5,6,7 is the second row of the matrix
matrix1

array([[2, 3, 4],
       [5, 6, 7]])

In [8]:
type(matrix1)

numpy.ndarray

In [9]:
matrix2 = np.array([[3,7,9,3],[4,3,2,2]])
matrix2
                    

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

In [10]:
x = np.random.rand(20)
x

array([0.56957278, 0.1247734 , 0.60556941, 0.44426716, 0.17063016,
       0.37025945, 0.86390114, 0.12782044, 0.17515389, 0.38756763,
       0.15203977, 0.31123491, 0.0129696 , 0.59925472, 0.7767719 ,
       0.80556203, 0.82949651, 0.6517611 , 0.64925482, 0.13031188])

In [11]:
x = np.random.rand(3,4)
x

array([[0.38407793, 0.31030929, 0.0410783 , 0.0160686 ],
       [0.51572219, 0.7521534 , 0.45118137, 0.9639193 ],
       [0.28839919, 0.88747003, 0.91100301, 0.79193182]])

In [12]:
x = np.random.randint(1, 100)
x

13

In [13]:
x = np.random.randint(2,10, 5)
x

array([3, 3, 8, 2, 4])

In [14]:
x = np.arange(1,30)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [21]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [23]:
X = [5, 7, 20]
Y = [9, 15, 4]

In [24]:
Xarr = np.array(X)
Yarr = np.array(Y)

In [25]:
distance = np.sqrt(Xarr **2 + Yarr**2)
distance

array([10.29563014, 16.55294536, 20.39607805])

In [26]:
x = np.array([2,3,4,5,7,10,20])
x

array([ 2,  3,  4,  5,  7, 10, 20])

In [27]:
#Array slicing and indexing

x[5]

10

In [28]:
x[:3] = 0
x

array([ 0,  0,  0,  5,  7, 10, 20])

In [29]:
matrix = np.random.randint(1, 10, (4,4))
matrix

array([[1, 1, 6, 6],
       [7, 9, 1, 9],
       [6, 5, 7, 9],
       [9, 3, 8, 1]])

In [30]:
matrix[-1][0]

9

In [31]:
matrix2 = np.random.randint(-10,50, (5,5))
matrix2

array([[ 31,   2,  26,  20,  25],
       [ 24,  43,  -3,  -8,  24],
       [ -7,  34,  38,  34,  38],
       [-10,  28,  15,  32,   4],
       [  0,  18,  47,  13,  43]])

In [32]:
matrix2[4] = 0
matrix2

array([[ 31,   2,  26,  20,  25],
       [ 24,  43,  -3,  -8,  24],
       [ -7,  34,  38,  34,  38],
       [-10,  28,  15,  32,   4],
       [  0,   0,   0,   0,   0]])

In [33]:
matrix = np.random.randint(1, 10, (5,5))
matrix

array([[7, 1, 1, 1, 7],
       [8, 2, 7, 7, 2],
       [4, 8, 5, 4, 9],
       [8, 7, 3, 1, 6],
       [5, 4, 2, 8, 7]])

In [34]:
new_matrix = matrix[ matrix%2 != 0]

new_matrix

array([7, 1, 1, 1, 7, 7, 7, 5, 9, 7, 3, 1, 5, 7])

In [35]:
matrixX = np.random.randint(-10, 20, (5,5))
matrixX

array([[ 4,  6, 11,  3, 15],
       [ 5, -1,  9,  6,  1],
       [19, 18, 16, 14, 13],
       [-4,  6, -5,  2, 15],
       [15, 10,  3,  1, 11]])

In [36]:
#replace every negative number from the above matrix with 0
#and odd with 2
matrixX[matrixX<0] = 0
matrixX

array([[ 4,  6, 11,  3, 15],
       [ 5,  0,  9,  6,  1],
       [19, 18, 16, 14, 13],
       [ 0,  6,  0,  2, 15],
       [15, 10,  3,  1, 11]])

In [37]:
matrixX[matrixX%2 == 1] = -2
matrixX

array([[ 4,  6, -2, -2, -2],
       [-2,  0, -2,  6, -2],
       [-2, 18, 16, 14, -2],
       [ 0,  6,  0,  2, -2],
       [-2, 10, -2, -2, -2]])

In [38]:
import pandas as pd

In [39]:
bank_client_df = pd.DataFrame({'Client ID': [111, 222, 333, 444],
                             'Name': ['Ali', 'Hassan', 'Kamran', 'Ahtsham'],
                             'Net Worth [$]': [34000, 42000, 1999, 344311],
                             'Years with Bank': [3,1,7,6]})

bank_client_df

Client ID     Name  Net Worth [$]  Years with Bank
0        111      Ali          34000                3
1        222   Hassan          42000                1
2        333   Kamran           1999                7
3        444  Ahtsham         344311                6

In [40]:
type(bank_client_df)

pandas.core.frame.DataFrame

In [41]:
bank_client_df.head(2)

Client ID    Name  Net Worth [$]  Years with Bank
0        111     Ali          34000                3
1        222  Hassan          42000                1

In [42]:
bank_client_df.tail(1)

Client ID     Name  Net Worth [$]  Years with Bank
3        444  Ahtsham         344311                6

In [43]:
stocks_df = pd.DataFrame({'Stock Ticker Symbol':['AAPL', 'AMZN', 'T'],
                         'Price per Share [$]': [3500, 200, 40],
                         'Number of stocks': [3,4,6]})

stocks_df

Stock Ticker Symbol  Price per Share [$]  Number of stocks
0                AAPL                 3500                 3
1                AMZN                  200                 4
2                   T                   40                 6

In [44]:
stocks_value = stocks_df['Price per Share [$]'] * stocks_df['Number of stocks']

stocks_value.sum()

11540

In [51]:
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')

<class 'urllib.error.URLError'>: <urlopen error unknown url type: https>

<class 'AttributeError'>: module 'pexpect' has no attribute 'TIMEOUT'